"""Runtime hedge ratio resolution for bothside sizing.

Default behavior is static: use settings.bothside_hedge_kelly_mult.
When mode="optimized", load best_ratio from a JSON file generated by
scripts/optimize_hedge_ratio.py.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from src.config import settings

logger = logging.getLogger(__name__)


def resolve_hedge_kelly_mult(static_default: float | None = None) -> float:
    """Resolve hedge Kelly multiplier with safe fallback."""
    base = static_default if static_default is not None else settings.bothside_hedge_kelly_mult

    if settings.bothside_hedge_ratio_mode != "optimized":
        return max(0.3, min(0.8, base))

    path = Path(settings.bothside_hedge_ratio_file)
    if not path.exists():
        logger.warning(
            "Optimized hedge ratio file not found: %s (fallback=%.2f)",
            path,
            base,
        )
        return max(0.3, min(0.8, base))

    try:
        data = json.loads(path.read_text())
        ratio = float(data.get("best_ratio", base))
        return max(0.3, min(0.8, ratio))
    except Exception:
        logger.warning(
            "Failed to load optimized hedge ratio from %s (fallback=%.2f)",
            path,
            base,
            exc_info=True,
        )
        return max(0.3, min(0.8, base))
